name: create Docker Image
description: "A composite action that combines multiple steps"
inputs:
  dockerfile-path:
    description: "Reqired"
    required: true
  docker-image-name:
    description: "Reqired"
    required: true
  docker-user-name:
    description: "Reqired"
    required: true
  docker-password:
    description: "Reqired"
    required: true
runs:
  using: "composite"
  steps:
    - name: checkout code
      uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'corretto'
        cache: maven
    - name: Build with Maven
      shell: bash
      run: mvn -B package --file accounts/pom.xml
    - name: create image
      shell: bash
      run: echo ${{ inputs.docker-user-name }}
    - name: Clear Docker builder cache
      shell: bash
      run: docker builder prune -f
    - name: Print working directory
      shell: bash
      run: pwd
    - name: List all files in repository
      shell: bash
      run: ls -R .
    - name: List files in target directory
      shell: bash
      run: ls -R accounts/target/
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ inputs.docker-user-name }}
        password: ${{ inputs.docker-password }}
    - name: Build image
      shell: bash
      run: docker build . -t arushagarwal405/{{ inputs.docker-image-name }}:s4  --file ${{ inputs.dockerfile-path }}
    - name: push image
      shell: bash
      run: docker push arushagarwal405/{{ inputs.docker-image-name }}:s4
#    - name: Build and push
#      uses: docker/build-push-action@v5
#      with:
#        push: true
#        file: ${{ inputs.dockerfile-path }}
#        tags: arushagarwal405/${{ inputs.docker-image-name }}:s4
