name: create Docker Image
description: "A composite action that combines multiple steps"
inputs:
  dockerfile-path:
    description: "Reqired"
    required: true
runs:
  using: "composite"
  steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
    - name: create image
      shell: bash
      run: echo ${{inputs.dockerfile-path}}

