name: create Docker Image
description: "A composite action that combines multiple steps"
inputs:
  dockerfile-path:
    description: "Reqired"
    required: true
  docker-image-name:
    description: "Reqired"
    required: true
  docker-user-name:
    description: "Reqired"
    required: true
  docker-password:
    description: "Reqired"
    required: true
runs:
  using: "composite"
  steps:
    - name: checkout code
      uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'corretto'
        cache: maven
    - name: Build with Maven
      shell: bash
      run: mvn -B package --file accounts/pom.xml
    - name: create image
      shell: bash
      run: echo ${{ inputs.docker-user-name }}
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ inputs.docker-user-name }}
        password: ${{ inputs.docker-password }}
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        push: true
        tags: arushagarwal405/${{ inputs.docker-image-name }}:s4
