name: create Docker Image
description: "A composite action that combines multiple steps"
inputs:
  dockerfile-path:
    description: "Reqired"
    required: true
runs:
  using: "composite"
  steps:
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'corretto'
        cache: maven
        - name: Build with Maven
          run: mvn -B package --file pom.xml
    - name: create image
      shell: bash
      run: echo ${{inputs.dockerfile-path}}

