name: Build Applications
on:
  workflow_dispatch:
    inputs:
      input:
        description: Enter environment
      select_app:
        type: choice
        description: Select Application
        options:
          - All
          - Accounts
          - Cards
          - Loans
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: Deploy Account Applications
        if: ${{ github.event.inputs.select_app == 'All' || github.event.inputs.select_app == 'Accounts' }}
        uses: ./.github/actions/create-docker-image
        with:
          dockerfile-path: accounts/Dockerfile
          docker-image-name: accounts
          docker-user-name: ${{ secrets.DOCKERHUB_USERNAME }}
          docker-password : ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Deploy Cards Applications
        if: ${{ github.event.inputs.select_app == 'All' || github.event.inputs.select_app == 'Cards' }}
        uses: ./.github/actions/create-docker-image
          with:
            dockerfile-path: cards/Dockerfile
            docker-image-name: cards
            docker-user-name: ${{ secrets.DOCKERHUB_USERNAME }}
            docker-password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Deploy Loans Applications
        if: ${{ github.event.inputs.select_app == 'All' || github.event.inputs.select_app == 'Loans' }}
        uses: ./.github/actions/create-docker-image
          with:
            dockerfile-path: loans/Dockerfile
            docker-image-name: loans
            docker-user-name: ${{ secrets.DOCKERHUB_USERNAME }}
            docker-password: ${{ secrets.DOCKERHUB_TOKEN }}
