name: Build Applications
on:
  workflow_dispatch:
    inputs:
      input:
        description: Enter environment
      select_app:
        type: choice
        description: Select Application
        options:
          - All
          - Accounts
          - Cards
          - Loans
jobs:
  Build:
    runs-on: ubuntu-latest
    my-job:
      if: ${{ github.event.inputs.select_app == 'All' || github.event.inputs.select_app == 'Accounts' }}
      uses: ./.github/actions/create-docker-image
      with:
        dockerfile-path: accounts/Dockerfile
        docker-image-name: accounts
#    steps:
#      - name: Deploy Account Applications
#        if: ${{ github.event.inputs.select_app == 'All' || github.event.inputs.select_app == 'Accounts' }}
#        uses: ./.github/actions/create-docker-image
#        with:
#          dockerfile-path: accounts/Dockerfile
#          docker-image-name: accounts
#        secrets: inherit
#      - name: Deploy Cards Applications
#        if: ${{ github.event.inputs.select_app == 'All' || github.event.inputs.select_app == 'Cards' }}
#        run: echo "Cards run"
#      - name: Deploy Loans Applications
#        if: ${{ github.event.inputs.select_app == 'All' || github.event.inputs.select_app == 'Loans' }}
#        run: echo "Loans run"
