name: test
run-name: ${{ github.actor }} is testing out GitHub Actions
on:
  workflow_dispatch:
    inputs:
      input:
        description: Enter environment
      select_app:
        type: choice
        description: Select Application
        options:
          - All
          - Accounts
          - Cards
          - Loans
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      -name: checkout code
       uses: actions/checkout@v2

      -name: Deploy Account App
       if: ${{ github.event.inputs.select_app == "All" || github.event.inputs.select_app == "Accounts" }}
       run : echo "Account run"

